platform :ios, '8.0'
use_frameworks!

target 'recrutamento_concrete' do
pod 'Alamofire', '~> 3.0'
pod 'Font-Awesome-Swift'
pod 'DGElasticPullToRefresh'
end

target 'recrutamento_concreteTests' do

end

